### ISSUE TITLE
Cannot run program "jfrog": error=2, No such file or directory

### ISSUE THREAD

**Issue by daniyalj** [jfrog/jfrog-data-generator#2]
👋 

I am running the maven generator. I first built the image manually with the Dockerfile under /packages/maven and then ran:

`
 docker run --rm -e "ARTIFACTORY_URL=https://artifactory-artifactory.example.com/artifactory" -e "ARTIFACTORY_USER=admin" -e "ARTIFACTORY_PASSWORD=admin" -e "ARTIFACTORY_REPO=libs-release-local" maven-gen:latest 
`

Error I get is:

```
 What we are going to do?
        We are going to build  10  packages, each with  5  major versions, each one of those major version will have
          5  minor version. We are going to deploy  release  type of packages.
        Number of deployments into each version folder will be:  1 .
        Each version will have 4 maven files: jar, source jar, javadoc jar, pom. 
Each version will have additional 1 files, each file size is 1
Caught: java.io.IOException: Cannot run program "jfrog": error=2, No such file or directory
java.io.IOException: Cannot run program "jfrog": error=2, No such file or directory
	at GenerateMaven.generate(Runner.groovy:40)
	at Generator.init(Generator.groovy:60)
	at Generator$init.call(Unknown Source)
	at Runner.run(Runner.groovy:11)
Caused by: java.io.IOException: error=2, No such file or directory
	... 4 more
```

**Comment by daniyalj** [comment]
Experiencing the same issue when building images with the build.sh script

**Comment by daniyalj** [comment]
I think this might be the issue

**Comment by daniyalj** [comment]
I think this might be the issue.. 

In line https://github.com/jfrog/jfrog-data-generator/blob/master/packages/maven/Dockerfile#L7

`
RUN curl -fL https://getcli.jfrog.io | sh && ln -s /jfrog /usr/local/bin/jfrog
`

This returns a 404 when I am running this manually on my local machine

**Comment by arturo-aparicio** [comment]
Yes, it is because the CLI is currently having download issues. We are already working on it and this should work after that is fixed.

**Comment by arturo-aparicio** [comment]
This should be resolved now. Please verify and close.

**Comment by daniyalj** [comment]
Its fixed thanks!
