### ISSUE TITLE
Maven generating sitting idol after running

### ISSUE THREAD

**Issue by daniyalj** [jfrog/jfrog-data-generator#3]
Hello I am running the maven generator to load test our artifactory HA server.

I am running:

After building the maven Docker image with build.sh , I am running:

`$ docker run --rm -e "ARTIFACTORY_URL=https://artifactory.example.com/artifactory" -e "ARTIFACTORY_USER=admin" -e "ARTIFACTORY_PASSWORD=admin" -e "ARTIFACTORY_REPO=libs-release" maven:0.1`

Output I am getting:

```
 What we are going to do?
        We are going to build  10  packages, each with  5  major versions, each one of those major version will have
          5  minor version. We are going to deploy  release  type of packages.
        Number of deployments into each version folder will be:  1 .
        Each version will have 4 maven files: jar, source jar, javadoc jar, pom. 
Each version will have additional 1 files, each file size is 1
Creating release versions for multi1
##MAVEN## ADD libs-release/org/jfrog/multi1/3.1/multi1-0-3.1.bin b25b0fbf46cef1d888fe900445c9ab95330f44cd
##MAVEN## ADD libs-release/org/jfrog/multi1/4.1/multi1-0-4.1.bin 3ce0a1af90b6e7a3dd8d45e410884b588ea2d04c
##MAVEN## ADD libs-release/org/jfrog/multi1/5.1/multi1-0-5.1.bin e9d71f5ee7c92d6dc9e92ffdad17b8bd49418f98
.. truncated ..
jfrog rt upload --server-id=art --flat=false --threads=15 --build-name=dummy-project --build-number=1544052259657 org/jfrog/multi1/ libs-release/
Stdout: The CLI commands require the Artifactory URL and authentication details
Stdout: Configuring JFrog CLI with these parameters now will save you having to include them as command options.
Stdout: You can also configure these parameters later using the 'config' command.
```

After getting the above output, it just sits and I dont see any activity in artifactory. Is this expected behaviour? Am I supposed to receive any feedback?

**Comment by arturo-aparicio** [comment]
This typically happens when the URL is not reachable. Please verify that the container is able to reach the artifactory instance you are trying to write to.

**Comment by daniyalj** [comment]
I had my artifactory server on http while I was doing https! Well if anyone else runs into this they can refer here. Thanks once again @jfrog-aparicio !
